[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "docker build -t trazanet ."

[deploy]
startCommand = "docker run -p ${PORT}:3000 trazanet"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 