[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 10
healthcheckInterval = 15
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 